### ISSUE TITLE
Datenbank/Yform: Datentypen vs. Feldverwendung

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/neues#114]
Hier mal einige Punkte, die mir in der Datenbank bzw. den YForm-Tablesets aufgefallen sind:

### be_user_id

- db-Feldtyp: `mediumtext`
- YForm-Feldtyp: `choice`=> `text`
- Verwendung: Referenz auf **einen** User in `rex_user`; (Feld `rex_user.id`, Typ `int unsigned`)

> Vorschlag: Ein Integer-Feld `int unsigned` sollte reichen 

### image

- db-Feldtyp: `text`
- YForm-Feldtyp: `be_media_preview` => `text`
- Verwendung: Bildname im Medienpool (Feld `rex_media.filename`, Typ `varchar(255)`)

> YForm-seitig kann das Feld nur `text`als Datentyp. Muss das in der Datenbank auch so sein? 

### status 

- db-Feldtyp: `text`
- YForm-Feldtyp: `choice`=> `text`
- Verwendung: Integer-Wert gem. Callback `Category::statusChoice`;

> Vorschlag: Umstellen auf `int`

### domain_ids

- db-Feldtyp: `text`
- YForm-Feldtyp: `text`
- Verwendung: Liste mit Integer-Wert als Referenz auf YRewrite; (Feld `rex_yrewrite_domain::id`, Typ `int unsigned`)

> Mit wievielen Domain-IDs müsste man realistisch maximal rechnen? Ein Feld von Typ `varchar(161)` nimmt 38 Ids auf (durchschnittliche Länge 4 Ziffern) oder 47 (3 Ziffern). Oder man nimmt direkt den Datentyp `set`. Dafür ist er da.

### image

- db-Feldtyp: `text`
- YForm-Feldtyp: `be_media_preview` => `text`
- Verwendung: Bildname im Medienpool (Feld `rex_media.filename`, Typ `varchar(255)`)
- besser: YForm kann hier nur TEXT

> YForm-seitig kann das Feld nur `text`als Datentyp. Muss das in der Datenbank auch so sein? 

Wegen PR #102 müssen eh bei einem neuen Release Änderungen im Tableset vorgenommen werden. Die Gelegenheit ist günstig, gleichzeitig weitere Optimierungen in Tabellen und Tablesets vorzunehmen.

**Comment by alxndr-w** [comment]
Alles richtig. Alles Dinge, bei denen ich meinte, dass ich diese schon Mal umgesetzt habe.

Wenn wir das geradeziehen, und das sollten wir unbedingt, können wir das als "Bug" behandeln imho und die Änderungen auch in einer Minor-Version durchführen.

Ich habe bewusst be_media_preview und domain als eigene Felder in yform_field angelegt. Wir können gerne die Möglichkeit für `varchar` und `set` dort als db-Feldtyp hinterlegen.

**Comment by alxndr-w** [comment]
https://github.com/FriendsOfREDAXO/neues/commit/5a62f3c2d3103f7672091787f6d5f7d05e89ac87

Ich konnte alles umsetzen bis auf das set für die domain_ids. Da kommt es zu SQL-Fehlern.

Dafür gerne ein neues Issue.

**Comment by alxndr-w** [comment]
Und natürlich auch `update_scheme.php` aktualisiert: https://github.com/FriendsOfREDAXO/neues/commit/f8ecec996b3118ef52de6fa8be1706d559b3798a
