### ISSUE TITLE
Cronjob-Klassen vor 5.1.0 aktualisieren

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/neues#116]
**Description / Beschreibung**
Durch #93 ändern sich die Klassen. Bereits installierte Klassen funktionieren dann nicht mehr und müssen nachträglich noch per SQL geändert werden:

![image](https://github.com/user-attachments/assets/b228f96b-89a4-476c-9f67-e195bdcddf35)

z.B. 
alt: `rex_cronjob_neues_publish.type` = `"rex_cronjob_neues_publish"`
neu: `rex_cronjob_neues_publish.type` = `"FriendsOfRedaxo\Neues\Cronjob\Publish"`

**Comment by christophboecker** [comment]
Jaaaaa, ist im Code enthalten, nur leider mit dem klassischen Fehler: es wird auf die alte Klasse zugegriffen. Merge; ich hätte es wissen müssen. Korrigiere ich morgen in Ruhe.

https://github.com/FriendsOfREDAXO/neues/blob/3203c181d3939078c6741ba1bc826b6f1d1c18a8/install.php#L63-L78

Statt `Publish::class` hätte es `'FriendsOfRedaxo\\Neues\\Cronjob\\Publish'` sein müssen
