### ISSUE TITLE
Problem bei Domainsuche

### ISSUE THREAD

**Issue by iriswerner** [FriendsOfREDAXO/neues#128]
**TypeError:** Cannot use "::class" on string
**File:** src/addons/yform/plugins/manager/lib/yform/manager/search.php
**Line:** 135

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                   | Line     |
| -------------------------------------------- | ------------------------------------------------------ | -------- |
| rex_yform_manager_search->getQueryFilter     | src/addons/yform/plugins/manager/lib/yform/manager.php | 754      |
| rex_yform_manager->getDataListQuery          | src/addons/yform/plugins/manager/lib/yform/manager.php | 514      |
| rex_yform_manager->getDataPage               | src/addons/yform/plugins/manager/pages/data_edit.php   | 20       |
| include                                      | src/addons/neues/pages/yform.php                       | 76       |
| require                                      | src/core/lib/packages/package.php                      | 233      |
| rex_package->includeFile                     | src/core/lib/be/controller.php                         | 517      |
| rex_be_controller::{closure}                 | src/core/lib/util/timer.php                            | 56       |
| rex_timer::measure                           | src/core/lib/be/controller.php                         | 499      |
| rex_be_controller::includePath               | src/core/lib/be/controller.php                         | 465      |
| rex_be_controller::includeCurrentPageSubPath | src/addons/neues/pages/neues.php                       | 15       |
| require                                      | src/core/lib/packages/package.php                      | 233      |
| rex_package->includeFile                     | src/core/lib/be/controller.php                         | 517      |
| rex_be_controller::{closure}                 | src/core/lib/util/timer.php                            | 56       |
| rex_timer::measure                           | src/core/lib/be/controller.php                         | 499      |
| rex_be_controller::includePath               | src/core/lib/be/controller.php                         | 439      |
| rex_be_controller::includeCurrentPage        | src/core/backend.php                                   | 253      |
| require                                      | src/core/boot.php                                      | 157      |
| require                                      | public/redaxo/index.php                                | 12       |

</details>
<details>
<summary>System report (REDAXO 5.18.0, PHP 8.3.12, MariaDB 10.6.18)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.18.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.3.12     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.6.18 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/129.0.0.0 |
|      Protocol | HTTP/2.0         |
|         HTTPS | yes              |

| Packages                 |                      |
| -----------------------: | :------------------- |
|             2factor_auth | 2.3                  |
|             accessdenied | 3.0.0                |
|                  adminer | 2.0.2                |
|              auto_delete | 1.0.2                |
|                   backup | 2.9.1                |
|                 be_style | 3.5.0                |
|      be_style/customizer | 3.5.0                |
|          be_style/redaxo | 3.5.0                |
|          be_style_fluent | 4.0.2                |
|            cache_warm_up | 1.1.0-dev            |
|                     cke5 | 6.1.0                |
|                  cronjob | 2.11.0               |
|                developer | 3.9.2                |
|                   events | 5.0.3                |
|                  install | 2.12.1               |
|           mailer_profile | 1.3.1                |
|              maintenance | 3.2.1                |
|                   mblock | 3.4.13               |
|            media_manager | 2.17.0               |
| media_manager_responsive | 1.1.7                |
|                mediapool | 2.15.0               |
|         mediapool_rename | 1.0.0                |
|                 metainfo | 2.11.0               |
|                    mform | 8.0.4                |
|                    neues | 5.1.0-dev-2024-09-13 |
|                phpmailer | 2.14.0               |
|                  project | dev                  |
|                search_it | 6.11.2               |
|  search_it/documentation | 6.10.1               |
|          search_it/stats | 6.11.2               |
|               seocheckup | 1.6.8                |
|                 speed_up | 1.4.0                |
|                    sprog | 1.5.1                |
|                    staff | 1.4.1                |
|                structure | 2.17.2               |
|        structure/content | 2.17.2               |
|                 uploader | 2.4.2                |
|                      url | 2.1.0                |
|                    users | 2.11.0               |
|          wenns_sein_muss | 5.1.0                |
|                  ydeploy | 2.0.2                |
|                    yform | 4.2.1                |
|              yform/email | 4.2.1                |
|            yform/manager | 4.2.1                |
|               yform/rest | 4.2.1                |
|              yform/tools | 4.2.1                |
|              yform_field | 2.7.1                |
|            yform_geo_osm | 1.2.9                |
|    yform_spam_protection | 1.2.5                |
|                     ymca | 2.2.0                |
|                 yrewrite | 2.10.0               |
|        yrewrite_metainfo | 2.1.1                |
|              zip_install | 1.5.3                |

</details>

**Comment by alxndr-w** [comment]
Könnte evtl. ein YForm-Problem sein https://github.com/yakamara/yform/issues/1535

**Comment by alxndr-w** [comment]
Problemumgehung in https://github.com/alexplusde/yform_field/pull/87
