### ISSUE TITLE
Addon-Update setzt alle vorhandenen Einträge auf den Status -2

### ISSUE THREAD

**Issue by iriswerner** [FriendsOfREDAXO/neues#131]
Gibt leider keine ausführlichere Beschreibung. Beim Update des Addons wurden alle vorhandenen news_entry Einträge auf den Status -2 gesetzt. Späterer Übertrag per yDeploy beinhaltet das Problem nicht.

**Comment by iriswerner** [comment]
Habe das auf einer weiteren Installation ausprobiert. Alle Newsbeiträge waren im Status 1, nach dem Update des Addons, alle Beiträge im Status -2.

**Comment by eaCe** [comment]
Ich glaube man muss den Operator explizit setzen. `setWhere("Status = 2")`

**Comment by alxndr-w** [comment]
@eaCe weiter unten in derselben Datei: 

https://github.com/redaxo/redaxo/blob/01ac071452da4399296342d68087594acd990e5a/redaxo/src/core/lib/login/user_session.php#L81

Ich hab's auf dem Schirm, kann aber aktuell keinen Fix bereitstellen aus zeitlichen Gründen.

**Comment by alxndr-w** [comment]
Ich kann die Ursache darin wirklich nicht erkennen, aber die Schreibweise die verwendet wird, gilt als deprecated.

https://github.com/redaxo/redaxo/blob/01ac071452da4399296342d68087594acd990e5a/redaxo/src/core/lib/sql/sql.php#L607-L647
