### ISSUE TITLE
Migration zu FOR: News Manager-Klasse und Fragmente übernehmen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/neues#42]
Um die Kompatibilität bei der Migration zu verbessern, könnten noch die Fragmente in https://github.com/FriendsOfREDAXO/newsmanager/tree/master/fragments und die Hilfsmethoden aus https://github.com/FriendsOfREDAXO/newsmanager/blob/master/lib/NewsManager.php dazu übernommen werden. Das könnte die Migration erleichtern.

**Comment by eaCe** [comment]
Beispiele zu einfügen: https://github.com/FriendsOfREDAXO/content/blob/main/lib/content.php#L86-L143
Inhalte in Dateien packen. 
Zu klären wären Styles

**Comment by alxndr-w** [comment]
Die Ausgabe-Fragmente müssten eben auch noch angepasst werden. 

Die Module und Templates dazu sind ja relativ easy und ich würde sie auch nicht vorinstallieren, aber per Knopfdruck installieren lassen.

**Comment by alxndr-w** [comment]
@eaCe hast du da noch Muse, das dieses Jahr umzusetzen, bevor ich im Slack am 1.1. um 00:00 Uhr ein frohes Neues wünsche?

**Comment by eaCe** [comment]
@alxndr-w Ausgaben in Bootstrap 3? Oder was genau ist gemeint?
