### ISSUE TITLE
Kategorie-Auswahl geht  nicht

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/neues#51]
Bei Klick auf + geschieht nichts. 
Leider auch nichts in der Konsole. 

<img width="344" alt="Bildschirmfoto 2023-12-31 um 14 30 44" src="https://github.com/FriendsOfREDAXO/neues/assets/791247/bbffcea6-eb25-424b-b9ee-d821ad6784e8">

**Comment by alxndr-w** [comment]
Hängt mit #52 zusammen, vermute ich.

**Comment by eaCe** [comment]
Auswählen funktioniert bei mir...

**Comment by skerbis** [comment]
hmm bekomme  keine Auswahl. Frische Installation von REDAXO
