### ISSUE TITLE
Kategorie editieren geht nicht

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/neues#52]
Beim Versuch eine neu angelegte Kategorie zu editieren bekomme ich: 

`Transaktion wurde wegen folgendem Fehler nicht ausgeführt: Error while executing statement "select t0.id, t0.`category_ids` from `rex_neues_entry` t0 ORDER BY t0.`publishdate` DESC" using params []! SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.category_ids' in 'field list'`

**Comment by alxndr-w** [comment]
Ok, schaue ich mir heute direkt noch an.

**Comment by eaCe** [comment]
Funktioniert beides bei mir

**Comment by alxndr-w** [comment]
![image](https://github.com/FriendsOfREDAXO/neues/assets/3855487/d8384692-78dd-470c-ab0a-ddcb6c3ccd81)

Kann ich nicht nachvollziehen.

**Comment by skerbis** [comment]
scheint mit dem aktuellen Stand zu funktionieren

**Comment by eaCe** [comment]
Nun habe ich es auch. Weiß aber nicht warum

**Comment by alxndr-w** [comment]
Ich verstehe nicht, wie ich das reproduzieren können soll...

**Comment by alxndr-w** [comment]
Ich vermute, ich habe den Fehler in einem anderen Zusammenhang gefunden. Ein aktualisiertes Tableset kommt...
