### ISSUE TITLE
Neues vs. Aktuelles

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/neues#57]
Im Menü steht Aktuelles das AddOn heißt aber Neues? 
Nach der Installation sucht man einen Menüpunkt Neues.

**Comment by alxndr-w** [comment]
Neues war der einzige Key, der passend frei war.

**Comment by skerbis** [comment]
hmm der key aktuelles wäre noch frei. Aber ok.

**Comment by alxndr-w** [comment]
Oh wirklich? Hmm. Ich finde das generell nicht so schlimm, mein Addon für Mitarbeitende heißt auch Staff z.B. – aus Sicht der Redakteure wäre "Neues" verwirrend, ich mag aber auch den Namen dafür.
