### ISSUE TITLE
url2: Call to a member function hasRestrictions() on null

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/neues#58]
Beim Aufruf des URL-AddOns 

```
**Error:** Call to a member function hasRestrictions() on null
**File:** redaxo/src/addons/url/pages/generator.profiles.php
**Line:** 93
```

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                               | Line     |
| -------------------------------------------- | -------------------------------------------------- | -------- |
| url_generate_column_data                     | redaxo/src/core/lib/util/formatter.php             | 494      |
| rex_formatter::custom                        | redaxo/src/core/lib/util/formatter.php             | 31       |
| rex_formatter::format                        | redaxo/src/core/lib/list.php                       | 1073     |
| rex_list->formatValue                        | redaxo/src/core/lib/list.php                       | 1255     |
| rex_list->get                                | redaxo/src/addons/url/pages/generator.profiles.php | 266      |
| require                                      | redaxo/src/core/lib/packages/package.php           | 233      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php              | 505      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                 | 56       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php              | 506      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php              | 453      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/url/pages/index.php              | 17       |
| require                                      | redaxo/src/core/lib/packages/package.php           | 233      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php              | 505      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                 | 56       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php              | 506      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php              | 436      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                        | 241      |
| require                                      | redaxo/src/core/boot.php                           | 155      |
| require                                      | redaxo/index.php                                   | 9        |

</details>
<details>
<summary>System report (REDAXO 5.15.2-dev, PHP 8.1.26, MariaDB 10.6.12)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.2-dev |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.26     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.6.12 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Safari/17.2.1 |
|      Protocol | HTTP/1.0      |
|         HTTPS | yes           |

| Packages            |             |
| ------------------: | :---------- |
|             adminer | 1.9.3       |
|            be_style | 3.2.0       |
| be_style/customizer | 3.2.0       |
|     be_style/redaxo | 3.2.0       |
|                cke5 | 6.1.0       |
|             cronjob | 2.10.0      |
|               feeds | 4.0.7       |
|              forcal | 3.8.0       |
|            icecoder | 3.0.2       |
|             install | 2.11.1      |
|              mblock | 3.4.13      |
|       media_manager | 2.14.0      |
|           mediapool | 2.13.0      |
|      mediapool_exif | 3.0         |
|            metainfo | 2.10.0      |
|               mform | 8.0.0-beta1 |
|             minibar | 2.3.1       |
|               neues | 4.0.1       |
|              pdfout | 8.1.1       |
|           phpmailer | 2.12.0      |
|             project | dev         |
|    quick_navigation | 6.1.0       |
|           structure | 2.15.0      |
|   structure/content | 2.15.0      |
|                 url | 2.1.0       |
|               users | 2.10.0      |
|               yform | 4.1.1       |
|         yform/email | 4.1.1       |
|       yform/manager | 4.1.1       |
|         yform_field | 2.3.3       |
|            yrewrite | 2.10.0      |
|         zip_install | 1.4.0       |

</details>

**Comment by alxndr-w** [comment]
Lösung hierfür ist, als Artikel dem Profil einen bestehenden Artikel zu verwenden und keinen fiktiven.

Dazu die Artikel-ID kurz vor Ausführung durch bspw. den Startseiten-Artikel ersetzen:
https://github.com/FriendsOfREDAXO/neues/blob/39e7576f39229338a1536745dad19781f43aa327/install/rex_url_profile_neues_entry.sql#L4
https://github.com/FriendsOfREDAXO/neues/blob/39e7576f39229338a1536745dad19781f43aa327/install/rex_url_profile_neues_category.sql#L4

**Comment by tbaddade** [comment]
> Lösung hierfür ist, als Artikel dem Profil einen bestehenden Artikel zu verwenden und keinen fiktiven.

Was genau verstehst du hier unter **fiktiven** Artikel?

**Comment by alxndr-w** [comment]
Eine Artikel-Id, zu der es keinen Artikel gibt.

**Comment by tbaddade** [comment]
Kann man im URL Addon direkt nicht machen. Auch das Löschen des Artikels in der Strukturverwaltung wird eigentlich unterbunden. 

Verstehe nicht, wozu man das benötigt.

**Comment by alxndr-w** [comment]
Wozu man "Profile mitinstallieren" benötigt, deren Artikel man noch nicht kennt?

**Comment by skerbis** [comment]
Vorschlag. Das Profil nach Auswahl eines Artikels in den Einstellungen installieren. 
So kann es auch installiert werden wenn url2 erst später als dieses AddOn installiert wird.

**Comment by alxndr-w** [comment]
Es sollte trotzdem keinen Fehler erzeugen, der URL nicht mehr nutzbar macht imho

**Comment by tbaddade** [comment]
> Es sollte trotzdem keinen Fehler erzeugen, der URL nicht mehr nutzbar macht imho

Das ist richtig und wird auch gemacht. Ich wollte nur den Hintergrund wissen, wie so etwas zustande kommen kann und weshalb man das benötigt.

**Comment by eaCe** [comment]
Der Fehler bleibt bei mir bestehen, auch mit korrekter Article ID 
![grafik](https://github.com/FriendsOfREDAXO/neues/assets/2708231/8deae2ce-680e-49a5-911e-78ca377f0734)
